# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Andrew's music
tagline:          'Lyrics for you to sing along'
description:      'Lyrics for you to sing along'
url:              http://nnkennard.github.io/music
baseurl:          /

author:
  name:           'Neha Kennard'
  url:            https://twitter.com/nnkennard


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  formatted_songs:
    output: true
  songs:
    output: false
